### ISSUE TITLE
어플리케이션 예제 : Drawing Lines 번역

### ISSUE THREAD

**Issue by philoskim** [ClojureBridgeSeoul/curriculum#24]
이 부분 제가 번역하겠습니다.

**Comment by dalzony** [comment]
@philoskim 예, 이쪽은 따로 repo를 따놨습니다
다음 리포지토리에서 확인하시고 해주시면 됩니다.
감사합니다~!!

https://github.com/ClojureBridgeSeoul/drawing/issues
