### ISSUE TITLE
/korean/outline/simple_values.md 번역

### ISSUE THREAD

**Issue by dalzony** [ClojureBridgeSeoul/curriculum#3]
https://github.com/ClojureBridgeSeoul/curriculum/blob/korean/outline/simple_values.md

**Comment by 11mia** [comment]
시작합니다!

**Comment by 11mia** [comment]
키워드에서 real world analog랑 boolean and nil 에서  truthiness를 어떻게 해석해야 할지 모르겠어요ㅠㅠ
